### ISSUE TITLE
Problems if GC runs during profiling? RangeError (0x003fdc710144c8 is recycled object)

### ISSUE THREAD

**Issue by brianhempel** [SamSaffron/memory_profiler#12]
I sometimes get the following error while generating the report for a very large action I am profiling.

```
RangeError (0x003fdc710144c8 is recycled object)
```

It triggers on this line after the block has finished:

```
report = MemoryProfiler.report do
```

Full gem backtrace:

```
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/results.rb:71:in `_id2ref'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/results.rb:71:in `block in string_report'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/results.rb:71:in `each'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/results.rb:71:in `map'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/results.rb:71:in `string_report'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/results.rb:58:in `register_results'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/reporter.rb:45:in `run'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler/reporter.rb:7:in `report'
~/.gem/ruby/2.2.0/gems/memory_profiler-0.0.4/lib/memory_profiler.rb:12:in `report'
```

I am running Ruby 2.2.0. Whether it errors or not appears to be random, but it may have to do with GC since it appears to be an access to something that doesn't exist.

Thanks for the gem. It's great (albeit slow) when it works!

**Comment by SamSaffron** [comment]
never seen this, but we should add a rescue for it.

**Comment by mperham** [comment]
:+1: I just got it on 3 out of 4 runs.

**Comment by SamSaffron** [comment]
can you chuck a rescue there and send through a PR ? want to make sure it corrects it

**Comment by Silox** [comment]
:+1: Experiencing the same issue here

**Comment by SamSaffron** [comment]
I thought I fixed this, is it still the case on master?

**Comment by epinault** [comment]
Same issue here. on OSX 10.10.3, with ruby 2.1.5 and memory_profiler 0.9.0 

Just the following sample code does it


```
require 'memory_profiler'
report = MemoryProfiler.report do
10000.times{|x|
t = "ell"
}

end
report.pretty_print
```

I get 

```
/Users/emmanuel/.gem/ruby/2.1.5/gems/memory_profiler-0.9.0/lib/memory_profiler/results.rb:71:in `_id2ref': 0x003ff5f9819fa0 is recycled object (RangeError)
	from /Users/emmanuel/.gem/ruby/2.1.5/gems/memory_profiler-0.9.0/lib/memory_profiler/results.rb:71:in `block in string_report'
	from /Users/emmanuel/.gem/ruby/2.1.5/gems/memory_profiler-0.9.0/lib/memory_profiler/results.rb:71:in `each'
	from /Users/emmanuel/.gem/ruby/2.1.5/gems/memory_profiler-0.9.0/lib/memory_profiler/results.rb:71:in `map'
	from /Users/emmanuel/.gem/ruby/2.1.5/gems/memory_profiler-0.9.0/lib/memory_profiler/results.rb:71:in `string_report'
```

**Comment by epinault** [comment]
I pulled master and using bundler and it is fixed for me

**Comment by SamSaffron** [comment]
cool will publish a new gem soon

**Comment by jmthomas** [comment]
Same problem here. :+1: for the new gem

**Comment by dgynn** [comment]
I believe we've eliminated the recycled objects issues with the 0.9.5 release. Please re-open a ticket if you see this again. Thanks!
