### ISSUE TITLE
Error on Ruby 2.2.1 & Rails 4.2

### ISSUE THREAD

**Issue by rishav** [SamSaffron/memory_profiler#35]
Running the profiler using: 

<pre>
<code>
require 'memory_profiler'

report = MemoryProfiler.report do
  require_relative '../config/environment'
  # Add specific code here if you want to profile deeper
end

report.pretty_print
</code>
</pre>

<pre>
<code>
/Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/top_n.rb:14:in `sort_by': comparison of Array with Array failed (ArgumentError)
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/top_n.rb:14:in `sort_by!'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/top_n.rb:14:in `top_n'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/results.rb:26:in `block in register_results'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/results.rb:24:in `each'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/results.rb:24:in `register_results'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:63:in `run'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:27:in `report'
	from /Users/rishav/.rvm/gems/ruby-2.2.1@edcast/gems/memory_profiler-0.9.6/lib/memory_profiler.rb:14:in `report'
</code>
</pre>

**Comment by rishav** [comment]
Some issue with my rails setup. Works on a clean setup.
